name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Kütüphaneleri kur
        run: pip install pyinstaller

      - name: EXE oluştur
        run: pyinstaller --onefile list.py

      - name: Dosyayı yükle
        uses: actions/upload-artifact@v4
        with:
          name: exe-file
          path: dist/*.exe